changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - major
    - title: Features
      labels:
        - minor
    - title: Bugfixes
      labels:
        - patch
    - title: Dependency updates
      labels:
        - dependencies
