name: Deploy Documentation

on:
  push:
    branches:
      - master  # Deploy on pushing to the default branch
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.0'
          extended: false

      - name: Install modules
        run: npm install
        working-directory: ./docs/

      - name: Build with Hugo
        run: npm run build
        working-directory: ./docs/

      - name: Deploy to target branch # Takes the content from publish_dir: which is going to gh-pages branch automatically.
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
