name: Deploy Documentation


on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.92.0'
          extended: true

      - name: Install modules
        run: npm install
        working-directory: ./docs/

      - name: Build with Hugo
        run: npm run build
        working-directory: ./docs/

      - name: Deploy to target branch # Takes the content from publish_dir: which is going to gh-pages branch automatically.
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public/
          tag_name: ${{ github.ref_name }}-${{ github.sha }}
