# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.20.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  automerge:
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@v2
       with:
         ref: ${{ github.event.pull_request.head.ref }}
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v2
       with:
        node-version: ${{ matrix.node-version }}
     - name: Approve a PR
       run: gh pr review --approve "$PR_URL" && gh pr merge --auto --merge  "$PR_URL"
       env:
         PR_URL: ${{github.event.pull_request.html_url}}
         GITHUB_TOKEN: ${{secrets.DEPENDABOT}}
  
  dependabot:
    needs: build
    runs-on: windows-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
     - uses: actions/checkout@v2
       with:
         ref: ${{ github.event.pull_request.head.ref }}
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v2
       with:
        node-version: ${{ matrix.node-version }}
     - name: Approve a PR
       if: ${{ needs.build.result == 'success' }}
       run: gh pr review --approve "$PR_URL" && gh pr merge --auto --merge  "$PR_URL"
       env:
         PR_URL: ${{github.event.pull_request.html_url}}
         GITHUB_TOKEN: ${{secrets.DEPENDABOT}}
